### ISSUE TITLE
Inhabited impossible

### ISSUE THREAD

**Issue by Ailrun** [Beluga-lang/Beluga#147]
For the next case, `impossible` is accepted even though some `step`s are inhabited with `[ ⊢ e_app_abs v_lam ]`.
```
% Copied from examples/tapl/ch6/small-step.bel and modified
LF term: type =
| lam: (term -> term) -> term
| app: term -> term -> term;

LF value:  term -> type =
| v_lam: value (lam M);

% ---------------------------------------------------------- %
% Small-step operational semantics

LF step: term -> term -> type =
| e_app_1    : step M1 M1'
             -> step (app M1 M2) (app M1' M2)
| e_app_2    : step M2 M2' -> value M1
              -> step (app M1 M2) (app M1 M2')
| e_app_abs : value M2
              -> step (app (lam M) M2) (M M2)
;

LF equal : term -> term -> type =
| refl: equal M M;

not_possible : type.

rec unique : [|- step M M1] -> [|- step M M2] -> [|- equal M1 M2 ] =
/ total s (unique m m1 m2 s)/
fn s1 => fn s2 => case s1 of
| [ |- e_app_1 DstepE1'] => impossible s1
| [ |- e_app_2 DstepE2' V1 ] => impossible s1
| [ |- e_app_abs V2] => impossible s1 % V2 is inhabited!
;
```

FYI, one-depth-shallow way is rejected as expected.
```
rec unique : [|- step M M1] -> [|- step M M2] -> [|- equal M1 M2 ] =
/ total s (unique m m1 m2 s)/
fn s1 => fn s2 => impossible s1
;
```

**Comment by tsani** [comment]
If you put the `e_app_abs` case first, it works!

This is because postponed unification constraints between branches bleed through to following branches. I encountered this issue a while back, and tried to prevent this.

Specifically, in `genObj` in `coverage.ml`, there is a call to `U.forceGloablCnstr` which forces all the postponed unification constraints that were accumulated during the earlier call to `genSpine`. Suppose 2 constraints are added. Suppose that solving the first constraint fails. Nothing deletes the second constraint from the list! During the checking of the following branch, this second constraint is still in the list, and if it is _also_ not satisfiable, then the pattern currently being analyzed is deemed impossible.

There are actually two levels of bleeding that occur here:
1. constraints can bleed through between different constructor patterns being tested against a given type (and this behaviour is intentional, judging from when I previously looked into this issue)
2. constraints can bleed through between *different branches* being analyzed. I think this is a bug. So it's probably a question of figuring out where is the most appropriate place to insert a call to `U.resetGlobalCnstrs`

**Comment by tsani** [comment]
I'm slightly mistaken.
`forceGlobalCnstrs` in `unify.ml` actually calls `resetGlobalCnstrs` as the first thing it does. However, solving constraints can introduce new constraints, so it is presumably these extra constraints that stick around.

**Comment by tsani** [comment]
I don't get why `s1` should be impossible in any of these cases. After all, you just did a split on `s1`, so there ought to be exactly 1 case for `s1` in each branch, no?

**Comment by Ailrun** [comment]
Yes, it should... I also don't know why. Furthermore, as I said in the above example, direct (without a split) impossible does not work...

**Comment by Ailrun** [comment]
@tsani Maybe I wrote the issue in a wrong way... What I mean is not that "won't work" case is wrong. Actually, `s1` is inhabited, so it should not be impossible. I will revise the text in this issue.

**Comment by tsani** [comment]
I was able to fix this by adding a reset for the global list of constraints in case of a failure. However, this does break one test that used a somewhat rare feature: strengthening. It appears that the coverage checker does not correctly strengthen metavariables synthesized in LF pattern spines.

**Comment by tsani** [comment]
To clarify: the reason the test broke is unrelated to my fix. That test should have been failing all along because of strengthening not working correctly. The only reason it used to work was because of the buggy behaviour of these global constraints. In fact, if we reorder things just right, we can get this test to fail without my fix in place!

I won't merge my fix until I can get strengthening to work correctly during coverage checking.

**Comment by Ailrun** [comment]
I'm not sure it is related with this issue or not, but here is another example.
```
LF term : type =
  | zero : term
;

LF formula : type =
  | eq     : term → term → formula
  | forall : (term → formula) → formula
;

LF true : formula → type =
  | ALL-E  : { s : term → formula }
             { t : term }
             true (forall s)
             → true (s t)
;

rec she_right:
    { S : [t : term ⊢ formula] }
    { P : [⊢ formula] }
    [⊢ true (forall (\t. S[t]))]
    → (({ T : [⊢ term] } [⊢ true S[T]]) → [⊢ true P])
    → [⊢ true P]
=
mlam S ⇒ mlam P ⇒ fn z ⇒ fn y ⇒
    let [⊢ Z] = z in
    y mlam T => [|- ALL-E (\t. S[t]) T Z]
;

rec she_wrong:
    { S : [t : term ⊢ formula] }
    { P : [⊢ formula] }
    [⊢ true (forall (\t. S[t]))]
    → (({ T : [⊢ term] } [⊢ true S[T]]) → [⊢ true P])
    → [⊢ true P]
=
mlam S ⇒ mlam P ⇒ fn z ⇒ fn y ⇒
    impossible y
;
```
