### ISSUE TITLE
Allow users to put multiple commands into a line

### ISSUE THREAD

**Issue by Ailrun** [Beluga-lang/Beluga#160]
For now, we need to write multiple lines of input to use multiple commands. However, for user experience, it would be helpful to allow multiple commands in a line.

**Comment by tsani** [comment]
Implementation guide:
- add a production called `interactive_harpoon_command_sequence` to `parser.ml` that uses `sep_by1` with a semicolon separator to parse a list of `interactive_harpoon_command`s.
- use this production in `prover.ml` to parse a sequence of commands instead of a single one
- call `process_command` on each until we run out or until one fails
- I don't think `process_command` indicates whether the command was executed successfully, so it will need to be adjusted.

**Comment by tsani** [comment]
Personally, I would like the behaviour of a multi-command to be that it succeeds only if *all* the commands succeeds. The naive implementation I'm about to write will chug along until a command fails, and *then* skip running the remaining commands.

Sadly, I can't implement the behaviour I really want because it depends on #152. We would have to create a session "snapshot" before executing the command sequence. If all the commands succeed, we discard the snapshot. If any command fails, we rollback to the snapshot.

I'll implement the naive code, and once we have resumable sessions, I'll adjust.
