### ISSUE TITLE
Harpoon omits the types of context variables in theorem types

### ISSUE THREAD

**Issue by Ailrun** [Beluga-lang/Beluga#209]
The last theorem in `t/harpoon/poplmark-reloaded/props.input` of 3c39b6addcb5ed3367fe660177308740307e8722 illustrates this issue.
When the original type of theorem is
```
proof Sn-abs : (g:cxt) {M : [g, x: tm A[] |- tm B[]]} Sn [g, x: tm A[] |- M] -> Sn [g |- (abs \x. M)]
```
harpoon generates
```
proof Sn-abs : (g : cxt) {M : (g, x : tm A[] |- tm B[])} Sn [g, x1 |- M] -> Sn [g |- abs (\x. M)]
```
(notes `g, x1 |-` part)  which gives an error message like
```
Need to know the type of bound variable x1.
Typically, a type annotation is required on a bound variable in order to disambiguate which schema element the variable is referring to.
```

**Comment by tsani** [comment]
This will need to be resolved the same way that it was resolved for
term-level `MApp`. The `MetaApp` constructor for `meta_spine` will
need to include a type annotation (a `meta_typ`) that can be used to
call the specialized pretty-printer for annotated meta-objects. This
printer will include the type annotations.

These variables appearing in the context are called bound variables
actually, not context variables.

**Comment by Ailrun** [comment]
@tsani oh, sorry for misuse of the word. What I intended is a bound variable which appears in the context part of contextual type.
Anyway, thank you for the solution. Will you  be going to fix this, or is it better to do it by myself?

**Comment by tsani** [comment]
I could work on it, but I probably won't get it done until tomorrow
night as I'm about to finish work today and tomorrow morning I have a
number of errands to run. If this bug is a showstopper for you, then
I'd recommend you take it, since you can probably fix it tomorrow
morning. It should just be a matter of adjusting the definition of
`meta_spine` in the internal syntax, fixing all the type errors that
result from that, and calling fmt_ppr_cmp_meta_obj_typed (iirc) in
prettyint to print the term correctly.

**Comment by Ailrun** [comment]
OK, I will tackle this.
