### ISSUE TITLE
Cannot use overshadowed LF type in proofs declared prior to the overshadowing

### ISSUE THREAD

**Issue by MartyO256** [Beluga-lang/Beluga#225]
Load the following signature:

```
LF term : type =;

LF term-eq : term -> term -> type =
| term-eq/i : term-eq M M
;

proof term-resp-term : { M : [ x : term |- term] } [ |- term-eq N N'] ->
                         [ |- term-eq (M[N]) (M[N'])] =
/ total /
intros
{ N : ( |- term), N' : ( |- term), M : (x : term |- term)
| eq : [ |- term-eq N N']
; split eq as
  case term-eq/i:
  { N' : ( |- term), M : (x : term |- term)
  | eq : [ |- term-eq N' N']
  ; ?
  }
}
;

LF term : type =;

LF term-eq : term -> term -> type =
| term-eq/i : term-eq E E
;
```

Completing the proof of `term-resp-term` with `solve [ |- term-eq/i ]` results in

```
Ill-typed expression.
    Expected type:
      term-eq (M[N']) (M[N'])
    Actual type:
      term-eq ?E_9[^0][] ?E_9[^0][]
```

Note that `type [ |- term-eq/i ]` yields

```
[ |- term-eq/i ] : [ |- term-eq ?E_9[^0][] ?E_9[^0][]]
```

as opposed to

```
[ |- term-eq/i ] : [ |- term-eq ?M_9[^0][] ?M_9[^0][]]
```

which indicates that the definition of `term-eq` declared after `term-resp-term` is used instead of the one prior.

Type reconstruction succeeds when the hole is manually replaced with `solve [ |- term-eq/i ]`.

**Comment by Ailrun** [comment]
Does it work without the latter definitions? I think it doesn't, and it's not a problem of overshadowing.

**Comment by MartyO256** [comment]
It works without the latter definition.

**Comment by Ailrun** [comment]
@tsani Could you take a look? It looks like signature loading has an issue.

**Comment by tsani** [comment]
The type error is a mismatch between `term-eq ?E ?E` and `term-eq M[N'] M[N']` so Beluga hasn't even unified the arguments because there is a head mismatch. It really seems like the issue is due to shadowing, especially since the problem goes away when you remove the second definition.
In general, we want to eventually forbid all shadowing for definitions (see #177) so I recommend adjusting the code to remove the shadowing. This is will fix your problem.

There is a related issue though due to the way Harpoon indexes terms. Here's some background:

When Harpoon indexes a term (resolves the text to a specific definition) it does this "at the end of the signature", so it will use the bottom-most definition, even if that definition isn't in scope at the point that the currently focused subgoal is located. This is a known issue, and I fixed it for references to theorems, which is the most complicated instance where this can show up (due to mutual blocks). Trying to access a definition that is below the active subgoal now produces an error. To make this work, every definition (theorems, LF, inductive, etc.) is internally equipped with a definition number, and for every kind of reference (except for theorems), one should only be allowed to access a definitions with a smaller definition number. So far, this is enforced for theorems only; one would need to write code to do this "late scopechecking" for all kinds of references. It's annoying to code up, but it's easy, I can explain in more detail where the code needs to go if someone wants to implement this.
