### ISSUE TITLE
beluga-highlight-holes is suddenly slow

### ISSUE THREAD

**Issue by adhameer** [Beluga-lang/Beluga#66]
As of 8267b59, the beluga-highlight-holes command has become significantly slower. After getting the message that the file has successfully loaded, there's a noticeable delay before the holes are highlighted. When there's only one hole in the file, the delay is about one second. When I use the following file, the delay is more like 8 seconds (these are estimates; I haven't actually timed it).

```
LF term : type =
   | true         : term
   | false        : term
   | if_then_else : term -> term -> term -> term
   | z            : term
   | succ         : term -> term
   | pred         : term -> term
   | iszero       : term -> term
;

LF value : term -> type =
   | v_zero     : value z
   | v_succ     : value V -> value (succ V)
   | v_true     : value true
   | v_false    : value false
;

let v : [|- value (succ (succ z))] = [|- v_succ (v_succ v_zero)];

let w : [x: term, v: value x |- value (succ (succ x))] =
    [x: term, v: value x |- v_succ (v_succ v)];

LF step: term -> term -> type =
   | e_if_true      : step (if_then_else true M2 M3) M2
   | e_if_false     : step (if_then_else false M2 M3) M3
   | e_pred_zero    : step (pred z) z
   | e_pred_succ    : value V
                      -> step (pred (succ V)) V
   | e_iszero_zero  : step (iszero z) true
   | e_iszero_succ  : value V
                      -> step (iszero (succ V)) false
   | e_if_then_else : step M1 M1'
                      -> step (if_then_else M1 M2 M3) (if_then_else M1' M2 M3)
   | e_succ         : step M N
                      -> step (succ M) (succ N)
   | e_pred         : step M N
                      -> step (pred M) (pred N)
   | e_iszero       : step M N
                      -> step (iszero M) (iszero N)
;

let e1 : [|- step (pred (succ (pred z))) (pred (succ z))] =
         [|- e_pred (e_succ e_pred_zero)] ;

let e2 : [|- step (pred (succ z)) z] = [|- e_pred_succ v_zero] ;

LF tp : type =
   | bool : tp
   | nat : tp
;

LF hastype : term -> tp -> type =
   | t_true   : hastype true bool
   | t_false  : hastype false bool
   | t_zero   : hastype z nat

   | t_if     : hastype M1 bool -> hastype M2 T -> hastype M3 T
		-> hastype (if_then_else M1 M2 M3) T

   | t_succ   : hastype M nat
		-> hastype (succ M) nat
   | t_pred   : hastype M nat
		-> hastype (pred M) nat
   | t_iszero : hastype M nat
		-> hastype (iszero M) bool
;

rec tps: [|- hastype M T] -> [|- step M N] -> [|- hastype N T] =
fn d => fn s => case s of
| [|- e_if_true]         => ?
| [|- e_if_false]        => ?
| [|- e_if_then_else S'] => ?
| [|- e_pred_zero]       =>
  let [|- t_pred _ ] = d in ?
| [|- e_pred_succ _]     => ?
| [|- e_iszero_zero]     => ?
| [|- e_iszero_succ _ ]  => ?
| [|- e_pred S']         => ?
| [|- e_succ S']         => ?
| [|- e_iszero S']       => ?
;
```

**Comment by pientka** [comment]
I agree -- I also have observed a substantial slowdown using the interactive mode.

**Comment by adhameer** [comment]
I looked into it further: the issue is present as of 8267b59. It could possibly have started at the previous commit (4b29fa8), but I can't tell because the version at that commit doesn't compile.

Both of these commits only change Beluga source files and not the emacs mode itself, but I can't replicate the slowdown when running the exact same commands in interactive mode (with `-emacs`) on the command line.

**Comment by tsani** [comment]
I profiled `beluga-highlight-holes` on Beluga HEAD and a number of helper functions that it calls. Here's a screenshot of my data:

![2018-05-04-093452_452x124_scrot](https://user-images.githubusercontent.com/903787/39630890-b6c17712-4f7e-11e8-99e8-6e9e9001a89d.png)

So pretty much all the time is taken up by loading the file and then all the calls to `beluga--wait`. This latter function checks to see if Beluga has sent a response terminator (a semicolon) and if not waits 400ms while Beluga generates some more output. `beluga--wait` is called in both `beluga--send` and `beluga--receive`. That pair of functions makes up `beluga--rpc` which is the primary function for interacting with the Beluga subprocess.

When performing `beluga-highlight-holes`, there's an initial `beluga--rpc` call to see how many holes there are, followed by two `beluga--rpc` calls for each hole. So for ten holes, that works out to:
`0.4s + 10 * 2 * 0.4 = 8.4s`. So indeed, Emacs spends all its time waiting.

Why didn't this happen before? My guess is that Emacs is now losing in a race against Beluga.

I believe that the change to using lookup strategies for holes introduced in 8267b59 has made Beluga ever so slightly slower. So what happens is this:

* Emacs sends a command to Beluga. Beluga starts working on the command.
* Emacs runs ahead and checks to see if Beluga has generated its output yet, and Beluga hasn't. (However, Beluga is *just* about to! That's why when trying out the same commands in the interactive mode manually there's no noticeable slowdown.)
* Emacs waits 400ms before checking again.
* Emacs finishes waiting and sees that Beluga has generated a complete response, so `beluga--wait` finishes.

I think that prior to 8267b59 this didn't happen since the code for parsing hole identifiers could always just assume the identifier was an integer, so Beluga would manage to generate a complete response before Emacs first checked to see whether a complete response was available. In other words, Emacs never needed to wait since it was slower than Beluga.

In my local copy, chaning the timeout from 400ms to 25ms brings down the overall `beluga-highlight-holes` time from 8.6s to 0.6s

**Comment by tsani** [comment]
New data with 25ms timeout:

![2018-05-04-100511_455x131_scrot](https://user-images.githubusercontent.com/903787/39632301-b3ec2b3c-4f82-11e8-8cd4-77bdf6e46997.png)
